---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rook-ceph
  name: rbd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
